#!/bin/bash

function pw3n_osx {
    say 'pawned you!'
    osascript -e 'tell app "Finder" to display dialog "Hacked by Russia!"' >/dev/null 2>&1
}

function pw3n_other {
    echo 'pw3nd by git prompt' | wall
}

case "$OSTYPE" in
  darwin*)  pw3n_osx;;
  *)   pw3n_other;;
esac
